### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by jacbrzam** [conda-forge/fredapi-feedstock#4]
### Additional comment:

Hello! The conda-forge version of this package is no longer compatible with Python >= 3.9.

**Comment by apjanke** [comment]
Hi, folks. We're running in to this problem too at my work. In Python 3.11, some calls error out apparently due to use of a [removed getchildren() method](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren) in the xml module.

```
  File "/opt-net/miniconda3/envs/py311/lib/python3.11/site-packages/fredapi/fred.py", line 158, in get_series_latest_release
    return self.get_series(series_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt-net/miniconda3/envs/py311/lib/python3.11/site-packages/fredapi/fred.py", line 135, in get_series
    for child in root.getchildren():
                 ^^^^^^^^^^^^^^^^
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

Could we get the new 0.5.1 or 0.5.2 fredapi version published soon? I see this PR for 0.5.1 - https://github.com/conda-forge/fredapi-feedstock/pull/5 - but the [PyPI release](https://pypi.org/project/fredapi/) is up to 0.5.2 now. We've tested 0.5.2 and it seems to work in Python 3.11.

**Comment by apjanke** [comment]
I put in a manual PR that fixes the linter complaints that look like they were holding up the merging of this and previous version updates: https://github.com/conda-forge/fredapi-feedstock/pull/7.

**Comment by adament** [comment]
This should be fixed now.
